[plugin]
repository = "https://github.com/belzaru17/WorkshopOptimizerPlugin.git"
commit = "1fc63f3eb572084f062dc30dcdb992ecac67206f"
owners = ["belzaru17"]
project_path = "WorkshopOptimizerPlugin"
changelog = "Updated to API10/FF7.0."
